version: '3.3'
services:
  postgres:
    image: postgres:9.6
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=12345
      - POSTGRES_DB=akka
    volumes:
      - ./schema.sql:/docker-entrypoint-initdb.d/schema.sql
