{
 "title": "Akka persistence",
 "time": { "from": "now-6h", "to": "now" },
 "templating": {
  "list": [
   { "name": "persistence_label", "label": "Akka persistence label", "query": "node,path" }
  ]
 },
 "panels": [
  {
   "title": "Recovery",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 },
   "collapsed": true,
   "panels": [
    {
     "title": "Global recoveries",
     "type": "graph",
     "description": "Akka persistence recoveries per second happening across entire cluster",
     "gridPos": { "h": 9, "w": 24, "x": 0, "y": 1 },
     "fieldConfig": { "defaults": { "unit": "reqps" } },
     "yaxes": [
      { "format": "reqps" }
     ],
     "targets": [
      {
       "expr": "sum(rate(promexample_akka_persistence_recovery_total[$__rate_interval]))",
       "legendFormat": "global"
      }
     ]
    },
    {
     "title": "Recoveries/s by $persistence_label",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 10 },
     "repeat": "persistence_label",
     "fieldConfig": { "defaults": { "unit": "reqps" } },
     "yaxes": [
      { "format": "reqps" }
     ],
     "targets": [
      {
       "expr": "sum by($persistence_label)(rate(promexample_akka_persistence_recovery_total[1m]))",
       "legendFormat": "{{$persistence_label}}"
      }
     ]
    },
    {
     "title": "Recoveries/s by $persistence_label",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 10 },
     "fieldConfig": { "defaults": { "unit": "reqps" } },
     "yaxes": [
      { "format": "reqps" }
     ],
     "targets": [
      {
       "expr": "sum by($persistence_label)(rate(promexample_akka_persistence_recovery_total[1m]))",
       "legendFormat": "{{$persistence_label}}"
      }
     ]
    },
    {
     "title": "Recovery average time",
     "type": "graph",
     "gridPos": { "h": 9, "w": 24, "x": 0, "y": 18 },
     "fieldConfig": { "defaults": { "unit": "ms" } },
     "yaxes": [
      { "format": "ms" }
     ],
     "targets": [
      {
       "expr": "sum(rate(promexample_akka_persistence_recovery_time_sum[$__rate_interval])) / sum(rate(promexample_akka_persistence_recovery_time_count[$__rate_interval]) > 0)",
       "legendFormat": "global"
      }
     ]
    },
    {
     "title": "Max recovery time",
     "type": "graph",
     "gridPos": { "h": 9, "w": 24, "x": 0, "y": 27 },
     "fieldConfig": { "defaults": { "unit": "ms" } },
     "yaxes": [
      { "format": "ms" }
     ],
     "targets": [
      {
       "expr": "max(max_over_time(promexample_akka_persistence_recovery_time{quantile='1'}[$__interval]))",
       "legendFormat": "global"
      }
     ]
    },
    {
     "title": "Recovery average time by $persistence_label",
     "type": "graph",
     "gridPos": { "h": 9, "w": 12, "x": 0, "y": 36 },
     "repeat": "persistence_label",
     "fieldConfig": { "defaults": { "unit": "ms" } },
     "yaxes": [
      { "format": "ms" }
     ],
     "targets": [
      {
       "expr": "sum by($persistence_label)(rate(promexample_akka_persistence_recovery_time_sum[$__rate_interval])) / sum by($persistence_label)(rate(promexample_akka_persistence_recovery_time_count[$__rate_interval]) > 0)",
       "legendFormat": "{{$persistence_label}}"
      }
     ]
    },
    {
     "title": "Max recovery time by $persistence_label",
     "type": "graph",
     "gridPos": { "h": 9, "w": 12, "x": 12, "y": 36 },
     "repeat": "persistence_label",
     "fieldConfig": { "defaults": { "unit": "ms" } },
     "yaxes": [
      { "format": "ms" }
     ],
     "targets": [
      {
       "expr": "max by($persistence_label)(max_over_time(promexample_akka_persistence_recovery_time{quantile='1'}[$__interval]))",
       "legendFormat": "{{$persistence_label}}"
      }
     ]
    },
    {
     "title": "Recovery average time by $persistence_label",
     "type": "graph",
     "gridPos": { "h": 9, "w": 12, "x": 0, "y": 45 },
     "fieldConfig": { "defaults": { "unit": "ms" } },
     "yaxes": [
      { "format": "ms" }
     ],
     "targets": [
      {
       "expr": "sum by($persistence_label)(rate(promexample_akka_persistence_recovery_time_sum[$__rate_interval])) / sum by($persistence_label)(rate(promexample_akka_persistence_recovery_time_count[$__rate_interval]) > 0)",
       "legendFormat": "{{$persistence_label}}"
      }
     ]
    },
    {
     "title": "Max recovery time by $persistence_label",
     "type": "graph",
     "gridPos": { "h": 9, "w": 12, "x": 12, "y": 45 },
     "fieldConfig": { "defaults": { "unit": "ms" } },
     "yaxes": [
      { "format": "ms" }
     ],
     "targets": [
      {
       "expr": "max by($persistence_label)(max_over_time(promexample_akka_persistence_recovery_time{quantile='1'}[$__interval]))",
       "legendFormat": "{{$persistence_label}}"
      }
     ]
    }
   ]
  },
  {
   "title": "Persistence event",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 1 },
   "collapsed": true,
   "panels": [
    {
     "title": "Global persistent events per second",
     "type": "graph",
     "description": "Akka persistent events per second happening across entire cluster",
     "gridPos": { "h": 9, "w": 24, "x": 0, "y": 2 },
     "fieldConfig": { "defaults": { "unit": "reqps" } },
     "yaxes": [
      { "format": "reqps" }
     ],
     "targets": [
      {
       "expr": "sum(rate(promexample_akka_persistence_persistent_event_total[$__rate_interval]))",
       "legendFormat": "global"
      }
     ]
    },
    {
     "title": "Persistent events per second by $persistence_label",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 11 },
     "repeat": "persistence_label",
     "fieldConfig": { "defaults": { "unit": "reqps" } },
     "yaxes": [
      { "format": "reqps" }
     ],
     "targets": [
      {
       "expr": "sum by($persistence_label)(rate(promexample_akka_persistence_persistent_event_total[$__rate_interval]))",
       "legendFormat": "{{$persistence_label}}"
      }
     ]
    },
    {
     "title": "Persistent events per second by $persistence_label",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 11 },
     "fieldConfig": { "defaults": { "unit": "reqps" } },
     "yaxes": [
      { "format": "reqps" }
     ],
     "targets": [
      {
       "expr": "sum by($persistence_label)(rate(promexample_akka_persistence_persistent_event_total[$__rate_interval]))",
       "legendFormat": "{{$persistence_label}}"
      }
     ]
    },
    {
     "title": "Persistent event average time",
     "type": "graph",
     "gridPos": { "h": 9, "w": 24, "x": 0, "y": 19 },
     "fieldConfig": { "defaults": { "unit": "ms" } },
     "yaxes": [
      { "format": "ms" }
     ],
     "targets": [
      {
       "expr": "sum(rate(promexample_akka_persistence_persistent_event_sum[$__rate_interval])) / sum(rate(promexample_akka_persistence_persistent_event_count[$__rate_interval]) > 0)",
       "legendFormat": "global"
      }
     ]
    },
    {
     "title": "Max persistent event time",
     "type": "graph",
     "gridPos": { "h": 9, "w": 24, "x": 0, "y": 28 },
     "fieldConfig": { "defaults": { "unit": "ms" } },
     "yaxes": [
      { "format": "ms" }
     ],
     "targets": [
      {
       "expr": "max(max_over_time(promexample_akka_persistence_persistent_event{quantile='1'}[$__interval]))",
       "legendFormat": "global"
      }
     ]
    },
    {
     "title": "Persistent event average time by $persistence_label",
     "type": "graph",
     "gridPos": { "h": 9, "w": 12, "x": 0, "y": 37 },
     "repeat": "persistence_label",
     "fieldConfig": { "defaults": { "unit": "ms" } },
     "yaxes": [
      { "format": "ms" }
     ],
     "targets": [
      {
       "expr": "sum by($persistence_label)(rate(promexample_akka_persistence_persistent_event_sum[$__rate_interval])) / sum by($persistence_label)(rate(promexample_akka_persistence_persistent_event_count[$__rate_interval]) > 0)",
       "legendFormat": "{{$persistence_label}}"
      }
     ]
    },
    {
     "title": "Max persistent event time time by $persistence_label",
     "type": "graph",
     "gridPos": { "h": 9, "w": 12, "x": 12, "y": 37 },
     "repeat": "persistence_label",
     "fieldConfig": { "defaults": { "unit": "ms" } },
     "yaxes": [
      { "format": "ms" }
     ],
     "targets": [
      {
       "expr": "max by($persistence_label)(max_over_time(promexample_akka_persistence_persistent_event{quantile='1'}[$__interval]))",
       "legendFormat": "{{$persistence_label}}"
      }
     ]
    },
    {
     "title": "Persistent event average time by $persistence_label",
     "type": "graph",
     "gridPos": { "h": 9, "w": 12, "x": 0, "y": 46 },
     "fieldConfig": { "defaults": { "unit": "ms" } },
     "yaxes": [
      { "format": "ms" }
     ],
     "targets": [
      {
       "expr": "sum by($persistence_label)(rate(promexample_akka_persistence_persistent_event_sum[$__rate_interval])) / sum by($persistence_label)(rate(promexample_akka_persistence_persistent_event_count[$__rate_interval]) > 0)",
       "legendFormat": "{{$persistence_label}}"
      }
     ]
    },
    {
     "title": "Max persistent event time time by $persistence_label",
     "type": "graph",
     "gridPos": { "h": 9, "w": 12, "x": 12, "y": 46 },
     "fieldConfig": { "defaults": { "unit": "ms" } },
     "yaxes": [
      { "format": "ms" }
     ],
     "targets": [
      {
       "expr": "max by($persistence_label)(max_over_time(promexample_akka_persistence_persistent_event{quantile='1'}[$__interval]))",
       "legendFormat": "{{$persistence_label}}"
      }
     ]
    }
   ]
  }
 ]
}