{
 "title": "Akka http",
 "time": { "from": "now-30m", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "http_label",
    "label": "Akka http labels",
    "query": "node,method,path,status,status_group"
   }
  ]
 },
 "panels": [
  {
   "title": "Rps",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 },
   "collapsed": true,
   "panels": [
    {
     "title": "Akka http global rps",
     "type": "graph",
     "description": "Global amount of rps experienced by entire cluster",
     "gridPos": { "h": 9, "w": 24, "x": 0, "y": 2 },
     "fieldConfig": { "defaults": { "unit": "reqps" } },
     "yaxes": [
      { "format": "reqps" }
     ],
     "targets": [
      {
       "expr": "sum(rate(promexample_akka_http_request_total[$__rate_interval]))"
      }
     ]
    },
    {
     "title": "$http_label",
     "type": "graph",
     "gridPos": { "h": 9, "w": 12, "x": 0, "y": 11 },
     "repeat": "http_label",
     "fieldConfig": { "defaults": { "unit": "reqps" } },
     "yaxes": [
      { "format": "reqps" }
     ],
     "targets": [
      {
       "expr": "sum by($http_label) (rate(promexample_akka_http_request_total[$__rate_interval]))",
       "legendFormat": "Rps by $http_labels "
      }
     ]
    },
    {
     "title": "$http_label",
     "type": "graph",
     "gridPos": { "h": 9, "w": 12, "x": 12, "y": 11 },
     "fieldConfig": { "defaults": { "unit": "reqps" } },
     "yaxes": [
      { "format": "reqps" }
     ],
     "targets": [
      {
       "expr": "sum by($http_label) (rate(promexample_akka_http_request_total[$__rate_interval]))",
       "legendFormat": "Rps by $http_labels "
      }
     ]
    },
    {
     "title": "$http_label",
     "type": "graph",
     "gridPos": { "h": 9, "w": 12, "x": 0, "y": 20 },
     "fieldConfig": { "defaults": { "unit": "reqps" } },
     "yaxes": [
      { "format": "reqps" }
     ],
     "targets": [
      {
       "expr": "sum by($http_label) (rate(promexample_akka_http_request_total[$__rate_interval]))",
       "legendFormat": "Rps by $http_labels "
      }
     ]
    },
    {
     "title": "$http_label",
     "type": "graph",
     "gridPos": { "h": 9, "w": 12, "x": 12, "y": 20 },
     "fieldConfig": { "defaults": { "unit": "reqps" } },
     "yaxes": [
      { "format": "reqps" }
     ],
     "targets": [
      {
       "expr": "sum by($http_label) (rate(promexample_akka_http_request_total[$__rate_interval]))",
       "legendFormat": "Rps by $http_labels "
      }
     ]
    },
    {
     "title": "$http_label",
     "type": "graph",
     "gridPos": { "h": 9, "w": 12, "x": 0, "y": 29 },
     "fieldConfig": { "defaults": { "unit": "reqps" } },
     "yaxes": [
      { "format": "reqps" }
     ],
     "targets": [
      {
       "expr": "sum by($http_label) (rate(promexample_akka_http_request_total[$__rate_interval]))",
       "legendFormat": "Rps by $http_labels "
      }
     ]
    }
   ]
  },
  {
   "title": "Response time",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 1 },
   "collapsed": true,
   "panels": [
    {
     "title": "Average global response time",
     "type": "graph",
     "description": "Average response time across whole cluster",
     "gridPos": { "h": 7, "w": 24, "x": 0, "y": 2 },
     "fieldConfig": { "defaults": { "unit": "ms" } },
     "yaxes": [
      { "format": "ms" }
     ],
     "targets": [
      {
       "expr": "sum(rate(promexample_akka_http_request_duration_sum[$__rate_interval])) / sum(rate(promexample_akka_http_request_duration_count[$__rate_interval]) > 0)",
       "legendFormat": "Avg"
      }
     ]
    },
    {
     "title": "Max response time",
     "type": "graph",
     "description": "Max response time observed across whole cluster",
     "gridPos": { "h": 7, "w": 24, "x": 0, "y": 9 },
     "fieldConfig": { "defaults": { "unit": "ms" } },
     "yaxes": [
      { "format": "ms" }
     ],
     "targets": [
      {
       "expr": "max_over_time(promexample_akka_http_request_duration{quantile='1'}[$__interval])",
       "legendFormat": "max"
      }
     ]
    },
    {
     "title": "Avg response time by $http_label ",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 16 },
     "repeat": "http_label",
     "fieldConfig": { "defaults": { "unit": "ms" } },
     "yaxes": [
      { "format": "ms" }
     ],
     "targets": [
      {
       "expr": "sum by($http_label)(rate(promexample_akka_http_request_duration_sum[$__rate_interval])) / sum by($http_label)(rate(promexample_akka_http_request_duration_count[$__rate_interval]) > 0)",
       "legendFormat": "{{$http_label}}"
      }
     ]
    },
    {
     "title": "Max response time by $http_label",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 16 },
     "repeat": "http_label",
     "fieldConfig": { "defaults": { "unit": "ms" } },
     "yaxes": [
      { "format": "ms" }
     ],
     "targets": [
      {
       "expr": "max by($http_label)(max_over_time(promexample_akka_http_request_duration{quantile='1'}[$__interval]))",
       "legendFormat": "{{$http_label}}"
      }
     ]
    },
    {
     "title": "Avg response time by $http_label ",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 24 },
     "fieldConfig": { "defaults": { "unit": "ms" } },
     "yaxes": [
      { "format": "ms" }
     ],
     "targets": [
      {
       "expr": "sum by($http_label)(rate(promexample_akka_http_request_duration_sum[$__rate_interval])) / sum by($http_label)(rate(promexample_akka_http_request_duration_count[$__rate_interval]) > 0)",
       "legendFormat": "{{$http_label}}"
      }
     ]
    },
    {
     "title": "Max response time by $http_label",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 24 },
     "fieldConfig": { "defaults": { "unit": "ms" } },
     "yaxes": [
      { "format": "ms" }
     ],
     "targets": [
      {
       "expr": "max by($http_label)(max_over_time(promexample_akka_http_request_duration{quantile='1'}[$__interval]))",
       "legendFormat": "{{$http_label}}"
      }
     ]
    },
    {
     "title": "Avg response time by $http_label ",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 32 },
     "fieldConfig": { "defaults": { "unit": "ms" } },
     "yaxes": [
      { "format": "ms" }
     ],
     "targets": [
      {
       "expr": "sum by($http_label)(rate(promexample_akka_http_request_duration_sum[$__rate_interval])) / sum by($http_label)(rate(promexample_akka_http_request_duration_count[$__rate_interval]) > 0)",
       "legendFormat": "{{$http_label}}"
      }
     ]
    },
    {
     "title": "Max response time by $http_label",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 32 },
     "fieldConfig": { "defaults": { "unit": "ms" } },
     "yaxes": [
      { "format": "ms" }
     ],
     "targets": [
      {
       "expr": "max by($http_label)(max_over_time(promexample_akka_http_request_duration{quantile='1'}[$__interval]))",
       "legendFormat": "{{$http_label}}"
      }
     ]
    },
    {
     "title": "Avg response time by $http_label ",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 40 },
     "fieldConfig": { "defaults": { "unit": "ms" } },
     "yaxes": [
      { "format": "ms" }
     ],
     "targets": [
      {
       "expr": "sum by($http_label)(rate(promexample_akka_http_request_duration_sum[$__rate_interval])) / sum by($http_label)(rate(promexample_akka_http_request_duration_count[$__rate_interval]) > 0)",
       "legendFormat": "{{$http_label}}"
      }
     ]
    },
    {
     "title": "Max response time by $http_label",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 40 },
     "fieldConfig": { "defaults": { "unit": "ms" } },
     "yaxes": [
      { "format": "ms" }
     ],
     "targets": [
      {
       "expr": "max by($http_label)(max_over_time(promexample_akka_http_request_duration{quantile='1'}[$__interval]))",
       "legendFormat": "{{$http_label}}"
      }
     ]
    },
    {
     "title": "Avg response time by $http_label ",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 48 },
     "fieldConfig": { "defaults": { "unit": "ms" } },
     "yaxes": [
      { "format": "ms" }
     ],
     "targets": [
      {
       "expr": "sum by($http_label)(rate(promexample_akka_http_request_duration_sum[$__rate_interval])) / sum by($http_label)(rate(promexample_akka_http_request_duration_count[$__rate_interval]) > 0)",
       "legendFormat": "{{$http_label}}"
      }
     ]
    },
    {
     "title": "Max response time by $http_label",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 48 },
     "fieldConfig": { "defaults": { "unit": "ms" } },
     "yaxes": [
      { "format": "ms" }
     ],
     "targets": [
      {
       "expr": "max by($http_label)(max_over_time(promexample_akka_http_request_duration{quantile='1'}[$__interval]))",
       "legendFormat": "{{$http_label}}"
      }
     ]
    }
   ]
  },
  { "title": "Connections", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 2 } },
  {
   "title": "Connections",
   "type": "graph",
   "description": "Http connections across whole cluster",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 3 },
   "fieldConfig": { "defaults": { "unit": "connections" } },
   "yaxes": [
    { "format": "connections" }
   ],
   "targets": [
    {
     "expr": "sum(promexample_akka_http_connections)",
     "legendFormat": "global"
    }
   ]
  },
  {
   "title": "Connections by node",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 3 },
   "fieldConfig": { "defaults": { "unit": "connections" } },
   "yaxes": [
    { "format": "connections" }
   ],
   "targets": [
    {
     "expr": "sum by(node) (promexample_akka_http_connections)",
     "legendFormat": "{{node}}"
    }
   ]
  }
 ]
}