{
 "title": "Akka cluster",
 "time": { "from": "now-5m", "to": "now" },
 "templating": {
  "list": [
   { "name": "cluster_label", "label": "Akka cluster label", "query": "node,region" }
  ]
 },
 "panels": [
  {
   "title": "Entities",
   "type": "row",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 0 },
   "collapsed": true,
   "panels": [
    {
     "title": "Entities",
     "type": "graph",
     "description": "Entities across entire cluster",
     "gridPos": { "h": 9, "w": 24, "x": 0, "y": 1 },
     "fieldConfig": { "defaults": { "unit": "entities" } },
     "yaxes": [
      { "format": "entities" }
     ],
     "targets": [
      {
       "expr": "sum(promexample_akka_cluster_entities_per_region)",
       "legendFormat": "global"
      }
     ]
    },
    {
     "title": "Entities perf$cluster_label",
     "type": "graph",
     "gridPos": { "h": 9, "w": 24, "x": 0, "y": 9 },
     "repeat": "cluster_label",
     "fieldConfig": { "defaults": { "unit": "entities" } },
     "yaxes": [
      { "format": "entities" }
     ],
     "targets": [
      {
       "expr": "sum by($cluster_label)(promexample_akka_cluster_entities_per_region)",
       "legendFormat": "{{$cluster_label}}"
      }
     ]
    }
   ]
  },
  { "title": "Shards", "type": "row", "gridPos": { "h": 9, "w": 24, "x": 0, "y": 1 } },
  {
   "title": "Shards",
   "type": "graph",
   "description": "Shards in entire cluster",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 2 },
   "fieldConfig": { "defaults": { "unit": "shards" } },
   "yaxes": [
    { "format": "shards" }
   ],
   "targets": [
    {
     "expr": "sum(promexample_akka_cluster_shards_per_region)",
     "legendFormat": "global"
    }
   ]
  },
  {
   "title": "Shards by $cluster_label",
   "type": "graph",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 10 },
   "repeat": "cluster_label",
   "fieldConfig": { "defaults": { "unit": "shards" } },
   "yaxes": [
    { "format": "shards" }
   ],
   "targets": [
    {
     "expr": "sum by($cluster_label) (promexample_akka_cluster_shards_per_region)",
     "legendFormat": "{{$cluster_label}}"
    }
   ]
  },
  {
   "title": "Shard regions on node",
   "type": "graph",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 18 },
   "fieldConfig": { "defaults": { "unit": "regions" } },
   "yaxes": [
    { "format": "regions" }
   ],
   "targets": [
    {
     "expr": "sum by(node)(promexample_akka_cluster_shard_regions_on_node)",
     "legendFormat": "{{node}}"
    }
   ]
  },
  { "title": "Reachability", "type": "row", "gridPos": { "h": 9, "w": 24, "x": 0, "y": 26 } },
  {
   "title": "Reachable nodes",
   "type": "graph",
   "description": "Amount of reachable nodes seen from perspective of individual nodes",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 27 },
   "fieldConfig": { "defaults": { "unit": "nodes" } },
   "yaxes": [
    { "format": "nodes" }
   ],
   "targets": [
    {
     "expr": "promexample_akka_cluster_reachable_nodes",
     "legendFormat": "{{node}}"
    }
   ]
  },
  {
   "title": "Unreachable nodes",
   "type": "graph",
   "description": "Amount of unreachable nodes seen from perspective of individual nodes",
   "gridPos": { "h": 9, "w": 24, "x": 12, "y": 27 },
   "fieldConfig": { "defaults": { "unit": "nodes" } },
   "yaxes": [
    { "format": "nodes" }
   ],
   "targets": [
    {
     "expr": "promexample_akka_cluster_unreachable_nodes > 0 ",
     "legendFormat": "{{node}}"
    }
   ]
  },
  {
   "title": "Nodes down",
   "type": "graph",
   "description": "Node down events seen seen from perspective of individual nodes",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 35 },
   "fieldConfig": { "defaults": { "unit": "nodes" } },
   "yaxes": [
    { "format": "nodes" }
   ],
   "targets": [
    {
     "expr": "floor(increase(promexample_akka_cluster_node_down_total[$__rate_interval])) > 0",
     "legendFormat": "{{node}}"
    }
   ]
  }
 ]
}